# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 742d09c25a051698c2de2484478dfd24b73ae80204c3ffd40407f43cfe8f43d4b17e09483c17329999902532bd9cf1410a7898fc38a10e665c5fd9c2afdf0e7b

test:
  secret_key_base: 3e7a59643a387da4562e6ff1181bf5b128742d48bd0a5d136199ac157a4254b6ed0b012185e1c61e7e7b6c0d0e6b1dadca1cefe90dfc8f539748fd9edf864611

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
